on:
  push:
    branches:
    - master
  
  release: 
    types: [created]
   
name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy-test
    runs-on: ubuntu-latest
    environment: production
    
    steps:

    - name: Show Working directory
      run: pwd  

    - name: Show Working directory
      run: ls -la  

    - name: Checkout
      uses: actions/checkout@v2

 
    - name: Terraform repo checkout
      uses: actions/checkout@v2  
      with:
          repository: Sophia-Rebecca12/Terraform
          token: ${{ secrets.MY_PAT }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Terraform
      run: |
        cd Instance_tf
        terraform init
        terraform plan
        terraform apply -auto-approve